- name: CentOS 7 repo
  shell: sed -e 's|^mirrorlist=|#mirrorlist=|g' -e 's|^#baseurl=http://mirror.centos.org|baseurl=https://mirrors.tuna.tsinghua.edu.cn|g' -i.bak /etc/yum.repos.d/CentOS-*.repo
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: CentOS 8 repo
  shell: sed -e 's|^mirrorlist=|#mirrorlist=|g' -e 's|^#baseurl=http://mirror.centos.org/$contentdir|baseurl=https://mirrors.tuna.tsinghua.edu.cn/centos|g' -i.bak /etc/yum.repos.d/CentOS-*.repo
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

- name: Ubuntu repo
  shell: sed -i 's/cn.archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
  when: ansible_distribution == "Ubuntu"