- name: firewalld and SELinux
  shell: systemctl disable --now firewalld && setenforce 0 && sed -i 's#SELINUX=enforcing#SELINUX=disabled#g' /etc/selinux/config
  ignore_errors: yes
  when: ansible_distribution == "CentOS"

- name: swap
  shell: sed -ri 's/.*swap.*/#&/' /etc/fstab && swapoff -a && sysctl -w vm.swappiness=0 

- name: change name
  raw: "echo {{hostname|quote}} > /etc/hostname"

- name: hostname
  shell: hostname {{hostname|quote}}
