- name: CentOS install packages
  yum:
    name: '{{ os_centos_packages_list }}'
    state: present
  when: ansible_distribution == "CentOS"

- name: Ubuntu install packages
  apt:
    name: '{{ os_ubuntu_packages_list }}'
    state: present
  when: ansible_distribution == "Ubuntu"
