- name: CentOS7 install packages
  yum:
    name: '{{ os_centos7_packages_list }}'
    state: present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: CentOS8 install packages
  yum:
    name: '{{ os_centos8_packages_list }}'
    state: present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

- name: Ubuntu install packages
  apt:
    name: '{{ os_ubuntu_packages_list }}'
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"