- name: Containerd
  shell: mkdir -p /etc/cni/net.d /opt/cni/bin && tar xf cni-plugins-linux-amd64-v*.tgz -C /opt/cni/bin/ && tar -xzf cri-containerd-cni-*-linux-amd64.tar.gz -C / && tar xf crictl-v*-linux-amd64.tar.gz -C /usr/bin/

- name: service config
  copy: 
    src: containerd.service
    dest: /etc/systemd/system/

- name: modo config
  copy: 
    src: containerd.conf
    dest: /etc/modules-load.d/

- name: sysctl config
  copy: 
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/

- name: sysctl
  shell: sysctl --system

- name: systemd modules
  service: 
    name: systemd-modules-load
    state: restarted
    enabled: yes

- name: creat config
  shell: mkdir -p /etc/containerd && containerd config default | tee /etc/containerd/config.toml && sed -i "s#SystemdCgroup\ \=\ false#SystemdCgroup\ \=\ true#g" /etc/containerd/config.toml && sed -i "s#k8s.gcr.io#registry.cn-hangzhou.aliyuncs.com/chenby#g" /etc/containerd/config.toml && sed -i 's#config_path\ \=\ \"\"#config_path\ \=\ \"/etc/containerd/certs.d\"#g' /etc/containerd/config.toml && mkdir /etc/containerd/certs.d/docker.io -pv && systemctl daemon-reload

- name: dockerhub config
  copy: 
    src: hosts.toml
    dest: /etc/containerd/certs.d/docker.io/

- name: crictl config 
  copy: 
    src: crictl.yaml
    dest: /etc/

- name: Containerd restart service
  service: 
    name: containerd
    state: restarted
    enabled: yes
