- name: monitoring-example.yaml
  copy: 
    src: 
      - monitoring-example.yaml
      - connectivity-check.yaml
    dest: /root/


- name: cilium helm
  shell: cd /root/ && tar xvf helm-*-linux-amd64.tar.tar -C /usr/local/bin/

- name: cilium
  shell: helm repo add cilium https://helm.cilium.io && helm install cilium cilium/cilium    --namespace kube-system    --set hubble.relay.enabled=true     --set hubble.ui.enabled=true    --set prometheus.enabled=true    --set operator.prometheus.enabled=true    --set hubble.enabled=true    --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,http}"

- name: cilium
  shell: cd /root/ && kubectl  apply -f monitoring-example.yaml && sed -i "s#google.com#oiox.cn#g" connectivity-check.yaml && kubectl  apply -f connectivity-check.yaml